sudo: required

language: node_js
node_js:
  - 8

services:
  - docker

before_install:
  - docker build -t jungomi/wabt .

script:
  - yarn run lint
  - yarn run test-coverage
  - yarn run compile-docker

notifications:
  email: false
